name: "GitHub Repo Mirror"

on:
  - push

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Mirror"
    steps:
      - uses: pkgstore/github-action-mirror@main
        with:
          source: "https://github.com/${{ github.repository }}"
          target: "${{ secrets.MIRROR_TARGET }}"
          username: "${{ secrets.MIRROR_USER_NAME }}"
          token: "${{ secrets.MIRROR_USER_TOKEN }}"
